server:
  port: 8090
  tomcat:
    uri-encoding: utf-8

spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    cache: false
    mode: HTML
    encoding: UTF-8

  redis:
    host: localhost
    port: 6379
    password: 1234
    timeout: 5000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
